# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd ..
          echo Downloading kzip...
          wget -q -O- https://www.jonof.id.au/files/kenutils/kzipmix-20200115-linux.tar.gz | tar -xz
          ls -1
          cd breeze16
          echo Deleting ignored files...
          xargs rm -r <zip-ignore.txt
          echo Remaining files:
          ls -1
          echo Running kzip...
          datetime=$(date +"%F.%H-%M-%S")
          echo $datetime
          echo "filename=breeze16-$datetime" >> $GITHUB_ENV
          ../kzipmix-20200115-linux/amd64/kzip -r -q ../breeze16-$datetime.zip *
          cd ..
          # zipinfo test-publish.zip
          ls
          echo current directory is $PWD

      - name: Upload published zip
        uses: actions/upload-artifact@v4
        with:
          name: breeze16-artifacts-test
          path: /home/runner/work/breeze16/${{env.filename}}.zip