name: Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set $datetime variable
        run: |
          echo datetime=$(date +"%F.%H-%M-%S") >> "$GITHUB_ENV"
          
      - name: Delete ignored files
        run: |
          echo Deleting ignored files...
          xargs rm -r <zip-ignore.txt
          echo Remaining files:
          ls -1
          
      - name: Upload loose files
        uses: actions/upload-artifact@v4
        with:
          name: breeze16-${{ env.datetime }}
          path: |
            /home/runner/work/breeze16/breeze16/assets/
            /home/runner/work/breeze16/breeze16/pack.png
            /home/runner/work/breeze16/breeze16/pack.mcmeta
            /home/runner/work/breeze16/breeze16/credits.txt
            /home/runner/work/breeze16/breeze16/respackopts.json5
            
      - name: Zip using kzip
        run: |
          cd ..
          echo Downloading kzip...
          wget -q -O- https://www.jonof.id.au/files/kenutils/kzipmix-20200115-linux.tar.gz | tar -xz
          ls -1
          cd breeze16
          echo Date and time string for filename is $datetime
          echo Running kzip...
          ../kzipmix-20200115-linux/amd64/kzip -r -q ../breeze16-$datetime.zip *
          cd ..
          echo Done, listing files in directory $PWD:
          ls -1
          
      - name: Upload published kzipped file
        uses: actions/upload-artifact@v4
        with:
          name: breeze16-${{ env.datetime }}-kzip
          path: /home/runner/work/breeze16/breeze16*.zip